'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Pix_Inovation_Chaves_Leatoria_e_Fixa.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_key_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_key_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Amigos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Amigos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bank_Account_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bank Account_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Binary_Code_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Binary_Code_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Browser_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Browser_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BTC_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BTC_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BTC_64x64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BTC_64x64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Close_50px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close_50px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copy_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DogeCoin_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DogeCoin_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DogeCoin_64x64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DogeCoin_64x64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Edit_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property email_send_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("email_send_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Erase_24x24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Erase_24x24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ethereum_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ethereum_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ethereum_64x64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ethereum_64x64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Exclamation_50px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exclamation_50px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property information_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("information_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property key_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LTC_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LTC_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LTC_64x64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LTC_64x64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property No_Bank_50px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("No_Bank_50px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property note_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ok_50px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok_50px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property order_history_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("order_history_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        '''</summary>
        Friend ReadOnly Property Pix() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Pix", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pix_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pix_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pix_2500x1472() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pix_2500x1472", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pix_275x99() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pix_275x99", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pix_630x452() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pix_630x452", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pix_64x64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pix_64x64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property qr_code_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("qr_code_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Question_mark_50px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question_mark_50px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property remove_key_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remove_key_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
